<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Chat content moderation
    |--------------------------------------------------------------------------
    | Messages containing links, social media, money-related content, or
    | banned keywords will be blocked to protect users and comply with policy.
    */

    /** Block any URL/link in messages */
    'block_links' => true,

    /** Social media domains to block (lowercase, without protocol) */
    'social_domains' => [
        'facebook.com',
        'fb.com',
        'fb.me',
        'instagram.com',
        'instagr.am',
        'twitter.com',
        'x.com',
        'tiktok.com',
        'snapchat.com',
        'linkedin.com',
        'youtube.com',
        'youtu.be',
        't.me',
        'telegram.me',
        'whatsapp.com',
        'wa.me',
        'discord.gg',
        'discord.com',
        'line.me',
        'wechat.com',
        'viber.com',
        'reddit.com',
        'pinterest.com',
        'tumblr.com',
        'onlyfans.com',
        'fans.ly',
    ],

    /** Money / payment / transaction phrases (whole-word or common phrases) */
    'money_phrases' => [
        'send me money',
        'send money',
        'send cash',
        'pay me',
        'paypal',
        'gcash',
        'paymaya',
        'cash app',
        'wire transfer',
        'bank transfer',
        'moneygram',
        'western union',
        'venmo',
        'buy load',
        'load me',
        'i need money',
        'need money',
        'loan me',
        'borrow money',
        'lend me',
        'investment opportunity',
        'invest here',
        'send ₱',
        'send peso',
        'send pesos',
        'send dollar',
        'send dollars',
        'send \$',
        'amount of',
        'transfer.*\d',
        'account number',
        'gcash number',
        'paymaya number',
        'mobile number.*pay',
    ],

    /** Banned keywords that void app policy (scam, solicitation, off-platform, etc.) */
    'banned_keywords' => [
        'scam',
        'scamming',
        'sugar daddy',
        'sugar mommy',
        'sugar baby',
        'escort',
        'hook up for money',
        'paid meet',
        'pay for meet',
        'meet for money',
        'sell.*body',
        'buy.*body',
        'illegal',
        'drugs',
        'drug deal',
        'fake id',
        'hack',
        'phishing',
        'click here',
        'dm me on ig',
        'dm me on instagram',
        'add me on fb',
        'add me on facebook',
        'message me on',
        'hit me up on',
        'contact me on',
        'my ig is',
        'my instagram',
        'my fb is',
        'my facebook',
        'follow me on',
        'check my ig',
        'check my profile on',
    ],
];
